/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetog;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author ALUNO
 */
public class telaAluno extends javax.swing.JFrame {

    /**
     * Creates new form teladois
     */
    public telaAluno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jTextField2 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTabbedPane6 = new javax.swing.JTabbedPane();
        jTextField12 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTabbedPane7 = new javax.swing.JTabbedPane();
        jTextField13 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTabbedPane30 = new javax.swing.JTabbedPane();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTabbedPane27 = new javax.swing.JTabbedPane();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jTabbedPane29 = new javax.swing.JTabbedPane();
        jTabbedPane28 = new javax.swing.JTabbedPane();
        jTabbedPane31 = new javax.swing.JTabbedPane();
        jTextField19 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton2.setText("Consultar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Excluir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Atualizar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton1.setText("Inserir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTabbedPane5.addTab("ID", jTextField2);
        jTabbedPane5.addTab("Nome", jTextField7);
        jTabbedPane5.addTab("Sexo", jTextField8);
        jTabbedPane5.addTab("Idade", jTextField9);
        jTabbedPane5.addTab("RG", jTextField6);

        jTabbedPane4.addTab("Informações Pessoais", jTabbedPane5);

        jTabbedPane6.addTab("ID", jTextField12);
        jTabbedPane6.addTab("Email", jTextField10);

        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });
        jTabbedPane6.addTab("Celular", jTextField11);

        jTabbedPane4.addTab("Contato", jTabbedPane6);

        jTabbedPane7.addTab("ID", jTextField13);
        jTabbedPane7.addTab("Rua", jTextField3);

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jTabbedPane7.addTab("Bairro", jTextField4);
        jTabbedPane7.addTab("Cidade", jTextField5);

        jTabbedPane4.addTab("Endereço", jTabbedPane7);

        jTabbedPane30.addTab("ID", jTextField14);
        jTabbedPane30.addTab("Forma de Pagamento", jTextField15);

        jTabbedPane4.addTab("Forma Pagamento", jTabbedPane30);

        jTextField16.setText("jTextField16");
        jTabbedPane27.addTab("Valor", jTextField16);

        jTextField17.setText("jTextField17");
        jTabbedPane27.addTab("Data Pagamento", jTextField17);

        jTextField18.setText("jTextField18");
        jTabbedPane27.addTab("Data Vencimento", jTextField18);
        jTabbedPane27.addTab("", jTabbedPane3);
        jTabbedPane27.addTab("", jTabbedPane29);
        jTabbedPane27.addTab("", jTabbedPane28);

        jTabbedPane4.addTab("Mensalidade", jTabbedPane27);

        jTabbedPane31.addTab("ID", jTextField19);
        jTabbedPane31.addTab("Livro", jTextField1);
        jTabbedPane31.addTab("Teste", jTextField20);

        jTabbedPane4.addTab("Módulo", jTabbedPane31);

        jMenu1.setText("Aluno");

        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem2.setText("Responsável");
        jRadioButtonMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jRadioButtonMenuItem2);

        jMenuItem1.setText("Professor");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem3.setText("Turma");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jTabbedPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jTabbedPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton1))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton2))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem2ActionPerformed
new Responsavel().setVisible(true); // mostra o formulário
 this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
new telaProfessor().setVisible(true); // mostra o formulário
 this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
new telaTurma().setVisible(true); // mostra o formulário
 this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
try{
            Conectar bd= new Conectar();
            bd.getConnection();
            Statement stmt = bd.conn.createStatement();
            
            String sql = "SELECT * FROM Alunos ";
            ResultSet rs = stmt.executeQuery(sql);
            
            
            while(rs.next()){
                System.out.println(rs.getInt("id_aluno"));
                System.out.println(rs.getInt("fk_informacoes"));            
                System.out.println(rs.getInt("fk_modulo"));
                System.out.println(rs.getInt("fk_formapag"));
                System.out.println(rs.getInt("fk_contato"));            
                System.out.println(rs.getInt("fk_mensalidade"));
                System.out.println(rs.getInt("fk_endereco"));
                              
                System.out.println("=====================");
            }
            bd.close();
            
        }catch(SQLException ex){
            System.out.println("Problema com SQL");
            ex.printStackTrace();
            
            
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
try{
            Conectar bd = new Conectar();
            bd.getConnection();
            Statement stmt = bd.conn.createStatement();
            
            String sqlinsert = "insert into Contato  (id_contato, email , celular) values (" +
                    jTextField12.getText() + ",'" + 
                    jTextField10.getText() + "','" +
                    jTextField11.getText() + "'); ";
                    
            
            String sqlinsert1 = "insert into Endereco ( id_endereco, rua, bairro, cidade) values (" +
                    jTextField13.getText() + ",'" + 
                    jTextField3.getText() + "','" +
                    jTextField4.getText() + "','" +
                    jTextField5.getText() + "'); ";
            
            String sqlinsert2 = "insert into  informacoes_pessoais (id_informacao, rg, idade, nome, sexo) values ( "+
                    jTextField2.getText() + ",'" +
                    jTextField6.getText() + "'," + 
                    jTextField9.getText() + ",'" +
                    jTextField7.getText() + "','" +
                    jTextField8.getText() + "'); ";
            
             String sqlinsert3 = "insert into modulo  (id_contato, email , celular) values (" +
                    jTextField12.getText() + ",'" + 
                    jTextField10.getText() + "','" +
                    jTextField11.getText() + "'); ";
                    
            
            
            stmt.executeUpdate(sqlinsert);
            stmt.executeUpdate(sqlinsert1);
            stmt.executeUpdate(sqlinsert2);
            stmt.executeUpdate(sqlinsert3);
            JOptionPane.showMessageDialog(null, "Gravação realizado com sucesso!");
            bd.close();   
        }catch(SQLException ex){
            System.out.println("Problema com SQL");
            ex.printStackTrace();
        }
                // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
  try{
                Conectar bd = new Conectar();
                bd.getConnection();
                Statement stmt = bd.conn.createStatement();
                String sqlinsert = "delete from Alunos where id_aluno = " + jTextField1.getText();
                stmt.executeUpdate(sqlinsert);
                JOptionPane.showMessageDialog(null, "Exclusão realizada com sucesso");
                
            }catch(SQLException ex){
                System.out.println("Problema com o SQL");
                ex.printStackTrace();
            }
                // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
try{
    Conectar bd = new Conectar();
    bd.getConnection();
    Statement stmt = bd.conn.createStatement();

//codigo pra atualizar os registros atraes dos valores existentes
String sql = "update alunos set fk_informacoes = " + jTextField2.getText() + ", fk_modulo= " + jTextField3.getText()+
        ", fk_formapaga= " + jTextField3.getText()+ 
         ", fk_contato= " + jTextField3.getText()+ 
        ", fk_mensalidade= " + jTextField3.getText()+ 
         ", fk_endereco= " + jTextField3.getText()+         
        "where id_aluno = " + jTextField1.getText();

stmt.executeUpdate(sql);
stmt.close();   
    
    
} catch(SQLException ex){
    System.err.println("SQLException: " + ex.getMessage());
}

//tela de confirmação dos dados atualizados
JOptionPane.showMessageDialog(null, "Registros atualizados com sucesso!");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaAluno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JTabbedPane jTabbedPane27;
    private javax.swing.JTabbedPane jTabbedPane28;
    private javax.swing.JTabbedPane jTabbedPane29;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane30;
    private javax.swing.JTabbedPane jTabbedPane31;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTabbedPane jTabbedPane6;
    private javax.swing.JTabbedPane jTabbedPane7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
